<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Import, Export, and Convert Data Files}
-->

# Import, Export, and Convert Data Files #

The idea behind **rio** is to simplify the process of importing data into R and exporting data from R. This process is, probably unnecessarily, extremely complex for beginning R users. Indeed, R supplies [an entire manual](http://cran.r-project.org/doc/manuals/r-release/R-data.html) describing the process of data import/export. And, despite all of that text, most of the packages described are (to varying degrees) out-of-date. Faster, simpler, packages with fewer dependencies have been created for many of the file types described in that document. **rio** aims to unify data I/O (importing and exporting) into two simple functions: `import` and `export` so that beginners (and experienced R users) never have to think twice (or even once) about the best way to read and write R data.

The core advantage of **rio** is that it makes assumptions that the user is probably willing to make. Specifically, **rio** uses the file extension of a file name to determine what kind of file it is. This is the same logic used by Windows OS, for example, in determining what application is associated with a given file type. By taking away the need to manually match a file type (which a beginner may not recognize) to a particular import or export function, **rio** allows almost all common data formats to be read with the same function.

By making import and export easy, it's an obvious next step to also use R as a simple data conversion utility. Transferring data files between various proprietary formats is always a pain and often expensive. The `convert` function therefore combines `import` and `export` to easily convert between file formats (thus providing a FOSS replacement for programs like [Stat/Transfer](https://www.stattransfer.com/) or [Sledgehammer](http://www.openmetadata.org/site/?page_id=1089)).

## Import ##

**rio** supports a huge number of file formats for data import. At the present time, this includes:

* txt (tab-seperated)
* tsv
* csv
* rds
* Rdata
* json
* dta (Stata)
* sav (SPSS)
* por (SPSS portable)
* sas7bdat (SAS)
* xpt (SAS XPORT)
* mtp (Minitab)
* rec (Epiinfo)
* syd (Systat)
* dif (Data Interchange Format)
* dbf ("XBASE" database files)
* xlsx (Excel)
* arff (Weka Attribute-Relation File Format)

[Examples coming here soon...]

## Export ##

The export capabilities of **rio** are somewhat more limited than the import capabilities, given the availability of different functions in various R packages and because import functions are often written to make use of data from other applications and it never seems to be a development priority to have functions to export to the formats used by other applications. That said, **rio** currently supports the following formats:

* txt (tab-seperated)
* tsv
* csv
* rds
* Rdata
* json
* dbf ("XBASE" database files)
* dta (Stata)
* sav (SPSS)
* xlsx (Excel)
* arff (Weka Attribute-Relation File Format)
* clipboard (on Mac and Windows only; as tab-separated data)


[Examples coming here soon...]

## Convert ##

The `convert` function links `import` and `export` by constructing a dataframe from the imported file and immediately writing it back to disk. `convert` invisibly returns the file name of the exported file, so that it can be used to programmatically access the new file.

[Examples coming here soon...]

It is also possible to use **rio** on the command-line by calling `Rscript` with the `-e` (expression) argument. For example, to convert a file from Stata (.dta) to comma-separated values (.csv), simply do the following:

```
Rscript -e "rio::convert('iris.dta', 'iris.csv')"
```
