context("Import")

#test_that("Import from TSV", {})
test_that("Import from CSV", {
    noheadercsv <- import(system.file("examples", "noheader.csv", package = "rio"), header = FALSE)
    expect_that(colnames(noheadercsv)[1], equals("V1"), label = "Header is correctly specified")
})
test_that("Import from CSVY", {
    d <- import(system.file("examples", "example.csvy", package = "rio"))
    expect_true(inherits(d, "data.frame"))
    
    d2 <- import(system.file("examples", "example2.csvy", package = "rio"))
    expect_true(all(c("title", "units", "source") %in% names(attributes(d2))))
})
#test_that("Import from PSV", {})
#test_that("Import from FWF", {})
#test_that("Import from RDS", {})
#test_that("Import from RDATA", {})
#test_that("Import from JSON", {})
#test_that("Import from Stata", {})
#test_that("Import from SPSS (.sav)", {})
#test_that("Import from SPSS (.por)", {})
#test_that("Import from XBASE", {})
#test_that("Import from Excel (.xls)", {})
#test_that("Import from Excel (.xlsx)", {})
#test_that("Import from Weka", {})
#test_that("Import from .R dump file", {})
#test_that("Import from XML", {})
#test_that("Import from SAS (.sas7bdat)", {})
#test_that("Import from SAS (.xpt)", {})
#test_that("Import from Minitab", {})
#test_that("Import from Epiinfo", {})
#test_that("Import from Systat", {})
#test_that("Import from DIF", {})
#test_that("Import from ODS", {})

