context("SQL dumps (sql) import")

sqldump <- system.file("examples/example.sql", package = "rio", mustWork = TRUE)
df_list <- import_list(sqldump)

test_that("SQL dump is imported as expected", {
  expect_equal(df_list,
               list(
                 # sqlite_sequence is always generated by SQLite
                 sqlite_sequence = data.frame(
                   name = c("test1", "test2"),
                   seq = c(2, 2),
                   stringsAsFactors = FALSE),
                 test1 = data.frame(
                   id = c(1, 2),
                   name1 = c("Ryan", "Thomas"),
                   stringsAsFactors = FALSE),
                 test2 = data.frame(
                   id = c(1, 2),
                   name2 = c("Ryan also", "Thomas also"),
                   stringsAsFactors = FALSE)))
})
