context("SQL dumps (sql) import")

test_that("SQLite dump is imported as expected", {
  sqlite_dump <- system.file("examples/example_sqlite_dump.sql",
                             package = packageName(), mustWork = TRUE)
  df_list <- import_list(sqlite_dump)
  
  expect_equal(df_list,
               list(
                 # sqlite_sequence is always generated by SQLite
                 sqlite_sequence = data.frame(
                   name = c("test1", "test2"),
                   seq = c(2, 2),
                   stringsAsFactors = FALSE),
                 test1 = data.frame(
                   id = c(1, 2),
                   name1 = c("Ryan", "Thomas"),
                   stringsAsFactors = FALSE),
                 test2 = data.frame(
                   id = c(1, 2),
                   name2 = c("Ryan also", "Thomas also"),
                   stringsAsFactors = FALSE)))
})

test_that("PostgreSQL dump is imported as expected", {
  postgres_dump <- system.file("examples/example_postgresql_dump.sql",
                               package = packageName(), mustWork = TRUE)
  iris_in_db <- iris
  colnames(iris_in_db) <- tolower(gsub("\\.", "_", colnames(iris_in_db)))
  
  expect_equal(import_list(postgres_dump), iris_in_db)
})
